version: "3.7"
services:
  postgis:
    image: postgis/postgis
    container_name: postgis
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      - ./data:/data
